### ISSUE TITLE
Add basic example in a real web application development context

### ISSUE THREAD

**Issue by benjamindulau** [beberlei/litecqrs-php#33]
When we first look at DDD in general and then give a try with a first implementation, we are immediatly stuck (well at least I was :p) at the point where since commands don't return any data, we don't know how to inform our user about what's happening.

This is even more confusing that we can read about anything and everything on the subject.

So, what do you think about providing an implementation example in a context of web application development ?

It could be something really common, like user registration:

``` PHP
<?php

namespace Acme\UserModule\Web\Controller;

class RegistrationController extends Controller
{
    public function registerAction(Request $request)
    {
        if ('POST' == $request->getMethod()) {            
            $this->getCommandBus()->handle(new RegisterCommand(
                $request->get('username'),
                $request->get('email'),
                $request->get('password')
            ));

            /*
             * Since commands don't return any data,
             * how to send messages back to the user ?
             * Such as success or failure messages ?
             * We'd like for instance to automatically log the user in
             * and then redirect him to a specific page...
             * 
             * Should we use a synchronous command bus and 
             * register an event handler that would do this ?
             * 
             * Or, should we query immediatly the model to verify its existence ?
             */

             // return $this->redirect('.....');
        }

        return $this->render(....); // render form template
    }
}
```

**Comment by ruudk** [comment]
I'd like to know that too. @beberlei Any tips?

**Comment by ruudk** [comment]
Already found out how to do this by looking at the [CRUDHelper.php](https://github.com/beberlei/litecqrs-php/blob/master/src/LiteCQRS/Plugin/SymfonyBundle/Controller/CRUDHelper.php#L46:L50)

Just use a try/catch. If no errors then it's a success. But how do you get the created user?

**Comment by henrikbjorn** [comment]
@ruudk query by using some of the data from the form?

**Comment by ruudk** [comment]
So there is no way to get the inserted ID for instance?

**Comment by ruudk** [comment]
What if I would add something that isn't unique and want to redirect to that page? Then I need the ID, right :)?

**Comment by benjamindulau** [comment]
@ruudk well, if you have a CQRS approach you don't manipulate things such as "inserted ID". This kind of architecture is meant to be scaled with no limit. Regarding this, you can't rely on an autoincrement. You need a GUID (UUID) which is unique across the whole system.

I have come to the conclusion that any part of the application is able to generate these GUIDs since they follow a RFC and your backend can easily validate them. So you can generate it from your client and have it before you even send your command to the command bus.

If you're not confortable with this, as @henrikbjorn said, you can also query the data from the read (query) layer just after the command was handled. In 99,99% of cases, the write operation shouldn't take more than a couple of seconds

So to deal with this delay you have several solutions: for instance redirect the user to a welcome page and by the time he goes back your data will be updated; You can also make use of the POST/REDIRECT/GET pattern which can addresses this; I have even seen some solutions based on some "wait" logic, but I'm not a fan.

**Comment by ruudk** [comment]
Thanks for your well explained reply. 

But GUID's are mostly in the format of `{3F2504E0-4F89-11D3-9A0C-0305E82C3301}`. But what if you just want some url like `http://localhost/posts/123/etc`? Do you first generate the GUID yourself, execute the command which auto increments an (int) id and also stores the GUID for later retrieval? 

Are there open-source applications that use this library?

**Comment by benjamindulau** [comment]
@ruudk Well, in theory having a CQRS approach doesn't really "requires" GUIDs, or anything for that matter. It's just about architectural patterns. Either you can implement patterns in a strict way, which will lead you to a command handler not returning anything or making use of GUIDs, either you can implement only some concepts from it, and decide to let handlers return information or else.

In this case you don't really do CQRS in a strict way, but you take what your application can benefit from it.

If you really need a CRUD, maybe you can't use the whole CQRS approach. But if you do, you need to stop thinking about traditional auto-incremented IDs because they don't fit.

So, for your question, I'd personally think about another way to build urls. In DDD (which is not a requirement here), an ID can be anything that can identify your entity, even a composition of several properties. An ID is not necessary something like an integer, autoincrement or whatever. For a customer it can be its email for instance ;-)

IMO, if you overlook at this, you will miss the point. If you really wan't to strictly implement CQRS, you need to change your point of view and to get rid of your old habits.

As for GUID, you can use this nice library: https://github.com/ramsey/uuid
