### ISSUE TITLE
Is JMS Serializer dependency really needed in AggregateRoot ?

### ISSUE THREAD

**Issue by benjamindulau** [beberlei/litecqrs-php#43]
Hi,

We are building something around CQRS and instead of reinventing the wheel, we'd like to make use of your library, which is really smart.

But actually we still have to extend your `AggregateRoot` base class just to get rid of the JMS Serializer dependency.

Is this dependency really needed here ? I think this is a little bit intrusive.

And if I refer to your comment into the code, I'd dare to bet that you share the thought ;-)

**Comment by beberlei** [comment]
Its not, we could change this to XML mapping

**Comment by beberlei** [comment]
but i guess for some people it might be a BC break :(

**Comment by benjamindulau** [comment]
You're right, it could break some existing codes :/

But IMO, this kind of change could justify a BC break since this is custom code and the dependency really has nothing to do here.

The decision is yours :/
If it can help, I'm ok for bearing with you the reponsability of the BC break. Moral support ;-)

**Comment by mbadolato** [comment]
Regardless, as I referenced in #37, the version of Serializer is locked to 0.9 for LiteCQRS. This is a huge issue. 

I was hoping it was simply a matter of fixing all of the use paths that broke when JMS broke out Serializer and SerializerBundle, but that wasn't enough. Then LCQRS also had a reliance on a few interfaces that JMS removed from the packages. 

We could simply remove the `use` lines requiring the interface files, but when it gets down to the Symfony plugin (which is what I'm using), there's a few parts that use Serializer's old way of doing things for registering handlers and whatnot (and that no longer exist in the packages) and I don't have the knowledge of the package to know what the original code was accomplishing, nor what needs to be done to convert to Serializer's newer way of doing things (and I haven't had the time to really dig into it to figure it out).

So, regardless, we already have some serious breaks (especially with Symfony) with Serializer, so changes and BC breaks could be just fine.

**Comment by borisguery** [comment]
:+1: the `AggregateRoot` should not be tied to an optional plugin. Especially given the important changes between Serializer versions.

**Comment by benjamindulau** [comment]
@beberlei Any plan about that ?

**Comment by beberlei** [comment]
planing to fix it by using xml metadata mapping only if serializer is enabled

**Comment by beberlei** [comment]
Should be fixed now
